/*----- PROTECTED REGION ID(Xspress3::DynAttrUtils.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Xspress3DynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the Xspress3 class
//
// project :     Xspress3
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Xspress3.h>
#include <Xspress3Class.h>

/*----- PROTECTED REGION END -----*/	//	Xspress3::DynAttrUtils.cpp

//================================================================
//  Attributes managed is:
//================================================================
//  DataChannel  |  Tango::DevDouble	Spectrum  ( max = 4096)
//================================================================

//	For compatibility reason, this file (Xspress3DynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//================================================================

namespace Xspress3_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a DataChannel dynamic attribute.
 *
 *  parameter attname: attribute name to be cretated and added.
 *  parameter ptr:     memory buffer used to set attribute value.
 *                     If NULL or not specified, buffer will be allocated.
 */
//--------------------------------------------------------
void Xspress3::add_DataChannel_dynamic_attribute(string attname, Tango::DevDouble *ptr)
{
	//	Attribute : DataChannel
	if (ptr==NULL)
		ptr = new Tango::DevDouble[4096];
	DataChannelAttrib	*datachannel = new DataChannelAttrib(attname);
	Tango::UserDefaultAttrProp	datachannel_prop;
	//	description	not set for DataChannel
	//	label	not set for DataChannel
	//	unit	not set for DataChannel
	//	standard_unit	not set for DataChannel
	//	display_unit	not set for DataChannel
	//	format	not set for DataChannel
	//	max_value	not set for DataChannel
	//	min_value	not set for DataChannel
	//	max_alarm	not set for DataChannel
	//	min_alarm	not set for DataChannel
	//	max_warning	not set for DataChannel
	//	min_warning	not set for DataChannel
	//	delta_t	not set for DataChannel
	//	delta_val	not set for DataChannel
	
	/*----- PROTECTED REGION ID(Xspress3::att_DataChannel_dynamic_attribute) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::att_DataChannel_dynamic_attribute
	datachannel->set_default_properties(datachannel_prop);
	//	Not Polled
	datachannel->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	DataChannel_data.insert(make_pair(attname, ptr));
	add_attribute(datachannel);
}
//--------------------------------------------------------
/**
 *	remove a DataChannel dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 *  parameter free_it: memory buffer will be freed if true or not specified.
 */
//--------------------------------------------------------
void Xspress3::remove_DataChannel_dynamic_attribute(string attname, bool free_it)
{
	remove_attribute(attname, true);
	map<string,Tango::DevDouble *>::iterator ite;
    if ((ite=DataChannel_data.find(attname))!=DataChannel_data.end())
    {
    	/*----- PROTECTED REGION ID(Xspress3::remove_DataChannel_dynamic_attribute) ENABLED START -----*/
    	
    	/*----- PROTECTED REGION END -----*/	//	Xspress3::remove_DataChannel_dynamic_attribute
		if (free_it)
			delete[] ite->second;
		DataChannel_data.erase(ite);
	}
}


//============================================================
//	Tool methods to get pointer on attribute data buffer 
//============================================================
//--------------------------------------------------------
/**
 *	Return a pointer on DataChannel data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevDouble *Xspress3::get_DataChannel_data_ptr(string &name)
{
	map<string,Tango::DevDouble *>::iterator ite;
    if ((ite=DataChannel_data.find(name))==DataChannel_data.end())
    {
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"Xspress3::get_DataChannel_data_ptr()");
    }
	return  ite->second;
}


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================


} //	namespace
