/*----- PROTECTED REGION ID(Xspress3Class.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        Xspress3Class.cpp
//
// description : C++ source for the Xspress3Class.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Xspress3 once per process.
//
// project :     Xspress3
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Xspress3Class.h>

/*----- PROTECTED REGION END -----*/	//	Xspress3Class.cpp

//-------------------------------------------------------------------
/**
 *	Create Xspress3Class singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Xspress3_class(const char *name) {
		return Xspress3_ns::Xspress3Class::init(name);
	}
}

namespace Xspress3_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
Xspress3Class *Xspress3Class::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		Xspress3Class::Xspress3Class(string &s)
 * description : 	constructor for the Xspress3Class
 *
 * @param s	The class name
 */
//--------------------------------------------------------
Xspress3Class::Xspress3Class(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering Xspress3Class constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(Xspress3Class::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::constructor

	cout2 << "Leaving Xspress3Class constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		Xspress3Class::~Xspress3Class()
 * description : 	destructor for the Xspress3Class
 */
//--------------------------------------------------------
Xspress3Class::~Xspress3Class()
{
	/*----- PROTECTED REGION ID(Xspress3Class::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		Xspress3Class::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
Xspress3Class *Xspress3Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new Xspress3Class(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		Xspress3Class::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
Xspress3Class *Xspress3Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartAcquisitionClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartAcquisitionClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartAcquisitionClass::execute(): arrived" << endl;
	((static_cast<Xspress3 *>(device))->start_acquisition());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopAcquisitionClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopAcquisitionClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopAcquisitionClass::execute(): arrived" << endl;
	((static_cast<Xspress3 *>(device))->stop_acquisition());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum Xspress3Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum Xspress3Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum Xspress3Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void Xspress3Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "NbCards";
	prop_desc = "Number of Xspress3 boxes";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MaxFrames";
	prop_desc = "";
	prop_def  = "16384";
	vect_data.clear();
	vect_data.push_back("16384");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BaseIPAddress";
	prop_desc = "";
	prop_def  = "192.168.0.1";
	vect_data.clear();
	vect_data.push_back("192.168.0.1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BasePort";
	prop_desc = "";
	prop_def  = "30123";
	vect_data.clear();
	vect_data.push_back("30123");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BaseMACAddress";
	prop_desc = "";
	prop_def  = "02.00.00.00.00.00";
	vect_data.clear();
	vect_data.push_back("02.00.00.00.00.00");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "NbChannels";
	prop_desc = "4, 6 or 8, depending on the firmware";
	prop_def  = "4";
	vect_data.clear();
	vect_data.push_back("4");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "CreateScopeModule";
	prop_desc = "";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ScopeModuleName";
	prop_desc = "";
	prop_def  = "None";
	vect_data.clear();
	vect_data.push_back("None");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Debug";
	prop_desc = "0 is off, 1 is on, 2 is verbose cardIndex = 0 (for a 1 xspress system)";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "CardIndex";
	prop_desc = "0 for a 1 xspress system";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ConfigFileDirectory";
	prop_desc = "Directory with configuration file. If None, not configuration \nfrom file will be applied.";
	prop_def  = "None";
	vect_data.clear();
	vect_data.push_back("None");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "InputImpedance";
	prop_desc = "0 -> High Impedance, 1 -> 50 Ohms (both TTL inputs)";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void Xspress3Class::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Xspress3");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Xspress3 detector server");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("Xspress3");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void Xspress3Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(Xspress3Class::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Xspress3(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Xspress3 *dev = static_cast<Xspress3 *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(Xspress3Class::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void Xspress3Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(Xspress3Class::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::attribute_factory_before
	//	Attribute : ExposureTime
	ExposureTimeAttrib	*exposuretime = new ExposureTimeAttrib();
	Tango::UserDefaultAttrProp	exposuretime_prop;
	exposuretime_prop.set_description("Exposure time");
	//	label	not set for ExposureTime
	exposuretime_prop.set_unit("s");
	//	standard_unit	not set for ExposureTime
	//	display_unit	not set for ExposureTime
	//	format	not set for ExposureTime
	exposuretime_prop.set_max_value("54");
	exposuretime_prop.set_min_value("0.000000025");
	//	max_alarm	not set for ExposureTime
	//	min_alarm	not set for ExposureTime
	//	max_warning	not set for ExposureTime
	//	min_warning	not set for ExposureTime
	//	delta_t	not set for ExposureTime
	//	delta_val	not set for ExposureTime
	
	exposuretime->set_default_properties(exposuretime_prop);
	//	Not Polled
	exposuretime->set_disp_level(Tango::OPERATOR);
	exposuretime->set_memorized();
	exposuretime->set_memorized_init(true);
	att_list.push_back(exposuretime);

	//	Attribute : NbFrames
	NbFramesAttrib	*nbframes = new NbFramesAttrib();
	Tango::UserDefaultAttrProp	nbframes_prop;
	//	description	not set for NbFrames
	//	label	not set for NbFrames
	//	unit	not set for NbFrames
	//	standard_unit	not set for NbFrames
	//	display_unit	not set for NbFrames
	//	format	not set for NbFrames
	//	max_value	not set for NbFrames
	nbframes_prop.set_min_value("0");
	//	max_alarm	not set for NbFrames
	//	min_alarm	not set for NbFrames
	//	max_warning	not set for NbFrames
	//	min_warning	not set for NbFrames
	//	delta_t	not set for NbFrames
	//	delta_val	not set for NbFrames
	
	nbframes->set_default_properties(nbframes_prop);
	//	Not Polled
	nbframes->set_disp_level(Tango::OPERATOR);
	nbframes->set_memorized();
	nbframes->set_memorized_init(true);
	att_list.push_back(nbframes);

	//	Attribute : TriggerMode
	TriggerModeAttrib	*triggermode = new TriggerModeAttrib();
	Tango::UserDefaultAttrProp	triggermode_prop;
	triggermode_prop.set_description("0 -> internal trigger, 1 -> external gate");
	//	label	not set for TriggerMode
	//	unit	not set for TriggerMode
	//	standard_unit	not set for TriggerMode
	//	display_unit	not set for TriggerMode
	//	format	not set for TriggerMode
	triggermode_prop.set_max_value("1");
	triggermode_prop.set_min_value("0");
	//	max_alarm	not set for TriggerMode
	//	min_alarm	not set for TriggerMode
	//	max_warning	not set for TriggerMode
	//	min_warning	not set for TriggerMode
	//	delta_t	not set for TriggerMode
	//	delta_val	not set for TriggerMode
	
	triggermode->set_default_properties(triggermode_prop);
	//	Not Polled
	triggermode->set_disp_level(Tango::OPERATOR);
	triggermode->set_memorized();
	triggermode->set_memorized_init(true);
	att_list.push_back(triggermode);

	//	Attribute : FileDir
	FileDirAttrib	*filedir = new FileDirAttrib();
	Tango::UserDefaultAttrProp	filedir_prop;
	filedir_prop.set_description("Path to the dector image files.");
	//	label	not set for FileDir
	//	unit	not set for FileDir
	//	standard_unit	not set for FileDir
	//	display_unit	not set for FileDir
	//	format	not set for FileDir
	//	max_value	not set for FileDir
	//	min_value	not set for FileDir
	//	max_alarm	not set for FileDir
	//	min_alarm	not set for FileDir
	//	max_warning	not set for FileDir
	//	min_warning	not set for FileDir
	//	delta_t	not set for FileDir
	//	delta_val	not set for FileDir
	
	filedir->set_default_properties(filedir_prop);
	//	Not Polled
	filedir->set_disp_level(Tango::OPERATOR);
	filedir->set_memorized();
	filedir->set_memorized_init(true);
	att_list.push_back(filedir);

	//	Attribute : LastFrame
	LastFrameAttrib	*lastframe = new LastFrameAttrib();
	Tango::UserDefaultAttrProp	lastframe_prop;
	lastframe_prop.set_description("Last acquired frame");
	//	label	not set for LastFrame
	//	unit	not set for LastFrame
	//	standard_unit	not set for LastFrame
	//	display_unit	not set for LastFrame
	//	format	not set for LastFrame
	//	max_value	not set for LastFrame
	//	min_value	not set for LastFrame
	//	max_alarm	not set for LastFrame
	//	min_alarm	not set for LastFrame
	//	max_warning	not set for LastFrame
	//	min_warning	not set for LastFrame
	//	delta_t	not set for LastFrame
	//	delta_val	not set for LastFrame
	
	lastframe->set_default_properties(lastframe_prop);
	//	Not Polled
	lastframe->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(lastframe);

	//	Attribute : FilePrefix
	FilePrefixAttrib	*fileprefix = new FilePrefixAttrib();
	Tango::UserDefaultAttrProp	fileprefix_prop;
	fileprefix_prop.set_description("Name of the file to store the data. The end .nxs will be automatically added.");
	//	label	not set for FilePrefix
	//	unit	not set for FilePrefix
	//	standard_unit	not set for FilePrefix
	//	display_unit	not set for FilePrefix
	//	format	not set for FilePrefix
	//	max_value	not set for FilePrefix
	//	min_value	not set for FilePrefix
	//	max_alarm	not set for FilePrefix
	//	min_alarm	not set for FilePrefix
	//	max_warning	not set for FilePrefix
	//	min_warning	not set for FilePrefix
	//	delta_t	not set for FilePrefix
	//	delta_val	not set for FilePrefix
	
	fileprefix->set_default_properties(fileprefix_prop);
	//	Not Polled
	fileprefix->set_disp_level(Tango::OPERATOR);
	fileprefix->set_memorized();
	fileprefix->set_memorized_init(true);
	att_list.push_back(fileprefix);

	//	Attribute : MCALength
	MCALengthAttrib	*mcalength = new MCALengthAttrib();
	Tango::UserDefaultAttrProp	mcalength_prop;
	mcalength_prop.set_description("Length of the MCA data to store. If 0 the maximum mca length will be saved.");
	//	label	not set for MCALength
	//	unit	not set for MCALength
	//	standard_unit	not set for MCALength
	//	display_unit	not set for MCALength
	//	format	not set for MCALength
	mcalength_prop.set_max_value("4096");
	mcalength_prop.set_min_value("0");
	//	max_alarm	not set for MCALength
	//	min_alarm	not set for MCALength
	//	max_warning	not set for MCALength
	//	min_warning	not set for MCALength
	//	delta_t	not set for MCALength
	//	delta_val	not set for MCALength
	
	mcalength->set_default_properties(mcalength_prop);
	//	Not Polled
	mcalength->set_disp_level(Tango::EXPERT);
	mcalength->set_memorized();
	mcalength->set_memorized_init(true);
	att_list.push_back(mcalength);

	//	Attribute : FramesPerFile
	FramesPerFileAttrib	*framesperfile = new FramesPerFileAttrib();
	Tango::UserDefaultAttrProp	framesperfile_prop;
	framesperfile_prop.set_description("Number of frames to save in each file. If 0 all frames will be in the same file.");
	//	label	not set for FramesPerFile
	//	unit	not set for FramesPerFile
	//	standard_unit	not set for FramesPerFile
	//	display_unit	not set for FramesPerFile
	//	format	not set for FramesPerFile
	//	max_value	not set for FramesPerFile
	//	min_value	not set for FramesPerFile
	//	max_alarm	not set for FramesPerFile
	//	min_alarm	not set for FramesPerFile
	//	max_warning	not set for FramesPerFile
	//	min_warning	not set for FramesPerFile
	//	delta_t	not set for FramesPerFile
	//	delta_val	not set for FramesPerFile
	
	framesperfile->set_default_properties(framesperfile_prop);
	//	Not Polled
	framesperfile->set_disp_level(Tango::EXPERT);
	framesperfile->set_memorized();
	framesperfile->set_memorized_init(true);
	att_list.push_back(framesperfile);

	//	Attribute : RunMode
	RunModeAttrib	*runmode = new RunModeAttrib();
	Tango::UserDefaultAttrProp	runmode_prop;
	runmode_prop.set_description("RunMode: playback, scope, scalers, hist, diag_hist, circular_buffer");
	//	label	not set for RunMode
	//	unit	not set for RunMode
	//	standard_unit	not set for RunMode
	//	display_unit	not set for RunMode
	//	format	not set for RunMode
	//	max_value	not set for RunMode
	//	min_value	not set for RunMode
	//	max_alarm	not set for RunMode
	//	min_alarm	not set for RunMode
	//	max_warning	not set for RunMode
	//	min_warning	not set for RunMode
	//	delta_t	not set for RunMode
	//	delta_val	not set for RunMode
	
	runmode->set_default_properties(runmode_prop);
	//	Not Polled
	runmode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(runmode);

	//	Attribute : DataCh1
	DataCh1Attrib	*datach1 = new DataCh1Attrib();
	Tango::UserDefaultAttrProp	datach1_prop;
	//	description	not set for DataCh1
	//	label	not set for DataCh1
	//	unit	not set for DataCh1
	//	standard_unit	not set for DataCh1
	//	display_unit	not set for DataCh1
	//	format	not set for DataCh1
	//	max_value	not set for DataCh1
	//	min_value	not set for DataCh1
	//	max_alarm	not set for DataCh1
	//	min_alarm	not set for DataCh1
	//	max_warning	not set for DataCh1
	//	min_warning	not set for DataCh1
	//	delta_t	not set for DataCh1
	//	delta_val	not set for DataCh1
	
	datach1->set_default_properties(datach1_prop);
	//	Not Polled
	datach1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(datach1);

	//	Attribute : DataCh2
	DataCh2Attrib	*datach2 = new DataCh2Attrib();
	Tango::UserDefaultAttrProp	datach2_prop;
	//	description	not set for DataCh2
	//	label	not set for DataCh2
	//	unit	not set for DataCh2
	//	standard_unit	not set for DataCh2
	//	display_unit	not set for DataCh2
	//	format	not set for DataCh2
	//	max_value	not set for DataCh2
	//	min_value	not set for DataCh2
	//	max_alarm	not set for DataCh2
	//	min_alarm	not set for DataCh2
	//	max_warning	not set for DataCh2
	//	min_warning	not set for DataCh2
	//	delta_t	not set for DataCh2
	//	delta_val	not set for DataCh2
	
	datach2->set_default_properties(datach2_prop);
	//	Not Polled
	datach2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(datach2);

	//	Attribute : DataCh3
	DataCh3Attrib	*datach3 = new DataCh3Attrib();
	Tango::UserDefaultAttrProp	datach3_prop;
	//	description	not set for DataCh3
	//	label	not set for DataCh3
	//	unit	not set for DataCh3
	//	standard_unit	not set for DataCh3
	//	display_unit	not set for DataCh3
	//	format	not set for DataCh3
	//	max_value	not set for DataCh3
	//	min_value	not set for DataCh3
	//	max_alarm	not set for DataCh3
	//	min_alarm	not set for DataCh3
	//	max_warning	not set for DataCh3
	//	min_warning	not set for DataCh3
	//	delta_t	not set for DataCh3
	//	delta_val	not set for DataCh3
	
	datach3->set_default_properties(datach3_prop);
	//	Not Polled
	datach3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(datach3);

	//	Attribute : DataCh4
	DataCh4Attrib	*datach4 = new DataCh4Attrib();
	Tango::UserDefaultAttrProp	datach4_prop;
	//	description	not set for DataCh4
	//	label	not set for DataCh4
	//	unit	not set for DataCh4
	//	standard_unit	not set for DataCh4
	//	display_unit	not set for DataCh4
	//	format	not set for DataCh4
	//	max_value	not set for DataCh4
	//	min_value	not set for DataCh4
	//	max_alarm	not set for DataCh4
	//	min_alarm	not set for DataCh4
	//	max_warning	not set for DataCh4
	//	min_warning	not set for DataCh4
	//	delta_t	not set for DataCh4
	//	delta_val	not set for DataCh4
	
	datach4->set_default_properties(datach4_prop);
	//	Not Polled
	datach4->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(datach4);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(Xspress3Class::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void Xspress3Class::command_factory()
{
	/*----- PROTECTED REGION ID(Xspress3Class::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::command_factory_before


	//	Command StartAcquisition
	StartAcquisitionClass	*pStartAcquisitionCmd =
		new StartAcquisitionClass("StartAcquisition",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartAcquisitionCmd);

	//	Command StopAcquisition
	StopAcquisitionClass	*pStopAcquisitionCmd =
		new StopAcquisitionClass("StopAcquisition",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopAcquisitionCmd);

	/*----- PROTECTED REGION ID(Xspress3Class::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		Xspress3Class::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void Xspress3Class::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(Xspress3Class::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		Xspress3Class::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void Xspress3Class::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Xspress3 *dev = static_cast<Xspress3 *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(Xspress3Class::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3Class::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3Class::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *Xspress3Class::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(Xspress3Class::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	Xspress3Class::Additional Methods
} //	namespace
