/*----- PROTECTED REGION ID(Xspress3StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Xspress3StateMachine.cpp
//
// description : State machine file for the Xspress3 class
//
// project :     Xspress3
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Xspress3.h>

/*----- PROTECTED REGION END -----*/	//	Xspress3::Xspress3StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace Xspress3_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_ExposureTime_allowed()
 *	Description : Execution allowed for ExposureTime attribute
 */
//--------------------------------------------------------
bool Xspress3::is_ExposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::ExposureTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::ExposureTimeStateAllowed_WRITE

	//	Not any excluded states for ExposureTime attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::ExposureTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::ExposureTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_NbFrames_allowed()
 *	Description : Execution allowed for NbFrames attribute
 */
//--------------------------------------------------------
bool Xspress3::is_NbFrames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for NbFrames attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::NbFramesStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::NbFramesStateAllowed_WRITE

	//	Not any excluded states for NbFrames attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::NbFramesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::NbFramesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_TriggerMode_allowed()
 *	Description : Execution allowed for TriggerMode attribute
 */
//--------------------------------------------------------
bool Xspress3::is_TriggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TriggerMode attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::TriggerModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::TriggerModeStateAllowed_WRITE

	//	Not any excluded states for TriggerMode attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::TriggerModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::TriggerModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_FileDir_allowed()
 *	Description : Execution allowed for FileDir attribute
 */
//--------------------------------------------------------
bool Xspress3::is_FileDir_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FileDir attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::FileDirStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FileDirStateAllowed_WRITE

	//	Not any excluded states for FileDir attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::FileDirStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FileDirStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_LastFrame_allowed()
 *	Description : Execution allowed for LastFrame attribute
 */
//--------------------------------------------------------
bool Xspress3::is_LastFrame_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LastFrame attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::LastFrameStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::LastFrameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_FilePrefix_allowed()
 *	Description : Execution allowed for FilePrefix attribute
 */
//--------------------------------------------------------
bool Xspress3::is_FilePrefix_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FilePrefix attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::FilePrefixStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FilePrefixStateAllowed_WRITE

	//	Not any excluded states for FilePrefix attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::FilePrefixStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FilePrefixStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_MCALength_allowed()
 *	Description : Execution allowed for MCALength attribute
 */
//--------------------------------------------------------
bool Xspress3::is_MCALength_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MCALength attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::MCALengthStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::MCALengthStateAllowed_WRITE

	//	Not any excluded states for MCALength attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::MCALengthStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::MCALengthStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_FramesPerFile_allowed()
 *	Description : Execution allowed for FramesPerFile attribute
 */
//--------------------------------------------------------
bool Xspress3::is_FramesPerFile_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FramesPerFile attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::FramesPerFileStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FramesPerFileStateAllowed_WRITE

	//	Not any excluded states for FramesPerFile attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::FramesPerFileStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::FramesPerFileStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_RunMode_allowed()
 *	Description : Execution allowed for RunMode attribute
 */
//--------------------------------------------------------
bool Xspress3::is_RunMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RunMode attribute in Write access.
	/*----- PROTECTED REGION ID(Xspress3::RunModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::RunModeStateAllowed_WRITE

	//	Not any excluded states for RunMode attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::RunModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::RunModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_DataCh1_allowed()
 *	Description : Execution allowed for DataCh1 attribute
 */
//--------------------------------------------------------
bool Xspress3::is_DataCh1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DataCh1 attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::DataCh1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::DataCh1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_DataCh2_allowed()
 *	Description : Execution allowed for DataCh2 attribute
 */
//--------------------------------------------------------
bool Xspress3::is_DataCh2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DataCh2 attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::DataCh2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::DataCh2StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_DataCh3_allowed()
 *	Description : Execution allowed for DataCh3 attribute
 */
//--------------------------------------------------------
bool Xspress3::is_DataCh3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DataCh3 attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::DataCh3StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::DataCh3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_DataCh4_allowed()
 *	Description : Execution allowed for DataCh4 attribute
 */
//--------------------------------------------------------
bool Xspress3::is_DataCh4_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DataCh4 attribute in read access.
	/*----- PROTECTED REGION ID(Xspress3::DataCh4StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::DataCh4StateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_StartAcquisition_allowed()
 *	Description : Execution allowed for StartAcquisition attribute
 */
//--------------------------------------------------------
bool Xspress3::is_StartAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartAcquisition command.
	/*----- PROTECTED REGION ID(Xspress3::StartAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::StartAcquisitionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Xspress3::is_StopAcquisition_allowed()
 *	Description : Execution allowed for StopAcquisition attribute
 */
//--------------------------------------------------------
bool Xspress3::is_StopAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StopAcquisition command.
	/*----- PROTECTED REGION ID(Xspress3::StopAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Xspress3::StopAcquisitionStateAllowed
	return true;
}

}	//	End of namespace
